{
 "title": "Powerwall History",
 "description": "An interactive view of your energy consumption, production, and environment.",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Solar Output",
   "type": "graph",
   "gridPos": { "h": 16, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "solar_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "solar" ], "type": "alias" }
      ],
      [
       { "params": [ "battery_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "battery" ], "type": "alias" }
      ],
      [
       { "params": [ "load_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "house" ], "type": "alias" }
      ],
      [
       { "params": [ "site_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "grid" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Solar Generated",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 0 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "solar_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      }
     ]
    }
   ]
  },
  {
   "title": "Current Solar Generation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "solar_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      }
     ]
    }
   ]
  },
  {
   "title": "Powerwall charge now",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "percentage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/system_status/soe"
      }
     ]
    }
   ]
  },
  {
   "title": "Total House Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 3 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "load_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      }
     ]
    }
   ]
  },
  {
   "title": "Current House Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 3 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "load_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Battery Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 6 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"battery_instant_power\") FROM \"http\" WHERE (\"url\" = 'https://teslapw/api/meters/aggregates' AND \"battery_instant_power\" > 0) AND $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "battery_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      },
      { "condition": "AND", "key": "battery_instant_power", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Current Battery Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 6 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"battery_instant_power\") FROM \"http\" WHERE (\"url\" = 'https://teslapw/api/meters/aggregates' AND \"battery_instant_power\" > 0) AND $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "battery_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      },
      { "condition": "AND", "key": "battery_instant_power", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Totals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 6 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "House",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"solar_instant_power\") AS \"solar\" FROM \"http\" WHERE (\"url\" = 'https://teslapw/api/meters/aggregates') AND $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "load_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      }
     ]
    },
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "solar_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "battery" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      }
     ]
    },
    {
     "alias": "Battery",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "battery_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "house" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      },
      { "condition": "AND", "key": "battery_instant_power", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "site_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "grid" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Grid Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 9 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"battery_instant_power\") FROM \"http\" WHERE (\"url\" = 'https://teslapw/api/meters/aggregates' AND \"battery_instant_power\" > 0) AND $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "site_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      },
      { "condition": "AND", "key": "site_instant_power", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Current Grid Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 9 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "query": "SELECT mean(\"battery_instant_power\") FROM \"http\" WHERE (\"url\" = 'https://teslapw/api/meters/aggregates' AND \"battery_instant_power\" > 0) AND $timeFilter GROUP BY time(1h) fill(none)",
     "select": [
      [
       { "params": [ "site_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      },
      { "condition": "AND", "key": "site_instant_power", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Total Grid Exported",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 12 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "site_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      },
      { "condition": "AND", "key": "site_instant_power", "operator": "<", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Solar Export",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 15, "y": 12 },
   "format": "watth",
   "valueName": "current",
   "targets": [
    {
     "alias": "Battery",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "battery_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      },
      { "condition": "AND", "key": "battery_instant_power", "operator": "<", "value": "0" }
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "site_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      },
      { "condition": "AND", "key": "site_instant_power", "operator": "<", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Power Breakdown",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 4, "x": 19, "y": 12 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "alias": "Solar",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "solar_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "solar" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      }
     ]
    },
    {
     "alias": "Battery",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "battery_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      },
      { "condition": "AND", "key": "battery_instant_power", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "site_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "grid" ], "type": "alias" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Grid Imported",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 14 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "site_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      },
      { "condition": "AND", "key": "site_instant_power", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Net Grid Cost",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 16 },
   "format": "currencyGBP",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "site_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000 * 0.11" ], "type": "math" }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      }
     ]
    }
   ]
  },
  {
   "title": "Net Grid Use",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 16 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http",
     "select": [
      [
       { "params": [ "site_instant_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "url",
       "operator": "=",
       "value": "https://teslapw/api/meters/aggregates"
      }
     ]
    }
   ]
  }
 ]
}